# yelp reviews sentimental analysis 

In [3]:
import pandas as pd 

df = pd.read_csv('yelp_reviews.csv')

df


Unnamed: 0             Name  \
0              0      Pecan Lodge   
1              1      Pecan Lodge   
2              2      Pecan Lodge   
3              3      Pecan Lodge   
4              4      Pecan Lodge   
...          ...              ...   
5670        5670  Marie’s Kitchen   
5671        5671  Marie’s Kitchen   
5672        5672  Marie’s Kitchen   
5673        5673  Marie’s Kitchen   
5674        5674  Marie’s Kitchen   

                                                  Link  \
0         https://m.yelp.com//biz/pecan-lodge-dallas-3   
1         https://m.yelp.com//biz/pecan-lodge-dallas-3   
2         https://m.yelp.com//biz/pecan-lodge-dallas-3   
3         https://m.yelp.com//biz/pecan-lodge-dallas-3   
4         https://m.yelp.com//biz/pecan-lodge-dallas-3   
...                                                ...   
5670  https://m.yelp.com//biz/marie-s-kitchen-dallas-2   
5671  https://m.yelp.com//biz/marie-s-kitchen-dallas-2   
5672  https://m.yelp.com//biz/marie-s-kitchen-dallas-2   
5673  https://m.yelp.com//biz/marie-s-kitchen-dallas-2   
5674  https://m.yelp.com//biz/marie-s-kitchen-dallas-2   

                                                 Review           Star  
0     I was skeptical about this whole new location ...  5 star rating  
1     Today was the 1st time I braved the long line ...  5 star rating  
2     I am almost too full to write this review. But...  4 star rating  
3     This is hands-down the best BBQ I've ever had ...  5 star rating  
4     Dropped in Yesterday (5/23), the first opening...  5 star rating  
...                                                 ...            ...  
5670  If youre looking for a filipino restaurant tha...  5 star rating  
5671  08Aug2019@1510:   The Tapsilog (one type of a ...  4 star rating  
5672  Was a bit skeptical initially because it's fou...  5 star rating  
5673  Perfect place to get a Filipino style breakfas...  5 star rating  
5674  Awesome find in North Dallas. The food is grea...  4 star rating  

[5675 rows x 5 columns]

In [4]:
df.columns 

Index(['Unnamed: 0', 'Name', 'Link', 'Review', 'Star'], dtype='object')

In [5]:
import string     # Imports the library
import nltk        # Imports the natural language toolkit
#nltk.download('stopwords')   # Download the stopwords dataset
#nltk.download('wordnet')
wn=nltk.WordNetLemmatizer()
from nltk.corpus import stopwords
stopwords.words('english')[0:10]

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [6]:
def text_process_lemmatize(revw):
    """
    Takes in a string of text, then performs the following:
    1. Remove all punctuation
    2. Remove all stopwords
    3. create a list of the cleaned text
    4. Return Lemmatize version of the list
    """
    
    # Replace the xa0 with a space
    revw=revw.replace('xa0',' ')
    
    # Check characters to see if they are in punctuation
    nopunc = [char for char in revw if char not in string.punctuation]
    # Join the characters again to form the string.
    nopunc = ''.join(nopunc)
    
    # Now just remove any stopwords
    token_text= [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    
    # perform lemmatization of the above list
    cleantext= ' '.join(wn.lemmatize(word) for word in token_text)
        
    return cleantext


df['LemmText']=df['Review'].apply(text_process_lemmatize)

In [11]:
df

Unnamed: 0             Name  \
0              0      Pecan Lodge   
1              1      Pecan Lodge   
2              2      Pecan Lodge   
3              3      Pecan Lodge   
4              4      Pecan Lodge   
...          ...              ...   
5670        5670  Marie’s Kitchen   
5671        5671  Marie’s Kitchen   
5672        5672  Marie’s Kitchen   
5673        5673  Marie’s Kitchen   
5674        5674  Marie’s Kitchen   

                                                  Link  \
0         https://m.yelp.com//biz/pecan-lodge-dallas-3   
1         https://m.yelp.com//biz/pecan-lodge-dallas-3   
2         https://m.yelp.com//biz/pecan-lodge-dallas-3   
3         https://m.yelp.com//biz/pecan-lodge-dallas-3   
4         https://m.yelp.com//biz/pecan-lodge-dallas-3   
...                                                ...   
5670  https://m.yelp.com//biz/marie-s-kitchen-dallas-2   
5671  https://m.yelp.com//biz/marie-s-kitchen-dallas-2   
5672  https://m.yelp.com//biz/marie-s-kitchen-dallas-2   
5673  https://m.yelp.com//biz/marie-s-kitchen-dallas-2   
5674  https://m.yelp.com//biz/marie-s-kitchen-dallas-2   

                                                 Review           Star  \
0     I was skeptical about this whole new location ...  5 star rating   
1     Today was the 1st time I braved the long line ...  5 star rating   
2     I am almost too full to write this review. But...  4 star rating   
3     This is hands-down the best BBQ I've ever had ...  5 star rating   
4     Dropped in Yesterday (5/23), the first opening...  5 star rating   
...                                                 ...            ...   
5670  If youre looking for a filipino restaurant tha...  5 star rating   
5671  08Aug2019@1510:   The Tapsilog (one type of a ...  4 star rating   
5672  Was a bit skeptical initially because it's fou...  5 star rating   
5673  Perfect place to get a Filipino style breakfas...  5 star rating   
5674  Awesome find in North Dallas. The food is grea...  4 star rating   

                                               LemmText  
0     skeptical whole new location business got hand...  
1     Today 1st time braved long line hype check say...  
2     almost full write review donning pant elastic ...  
3     handsdown best BBQ Ive ever entire lifeI actua...  
4     Dropped Yesterday 523 first opening day Pecan ...  
...                                                 ...  
5670  youre looking filipino restaurant made order l...  
5671  08Aug20191510 Tapsilog one type Filipino Break...  
5672  bit skeptical initially found inside office bu...  
5673  Perfect place get Filipino style breakfast als...  
5674  Awesome find North Dallas food great made fres...  

[5675 rows x 6 columns]

In [12]:
df_y = df['Star'].tolist()
ranks =[]
for i in df_y:
    star = int(i.split(" ")[0])
    ranks.append(star)
    
y= ranks

In [13]:
y

[5,
 5,
 4,
 5,
 5,
 4,
 4,
 5,
 5,
 2,
 2,
 5,
 4,
 2,
 1,
 4,
 4,
 5,
 3,
 2,
 5,
 5,
 4,
 5,
 5,
 4,
 4,
 5,
 5,
 2,
 2,
 5,
 4,
 2,
 1,
 4,
 4,
 5,
 3,
 2,
 5,
 5,
 4,
 5,
 5,
 4,
 4,
 5,
 5,
 2,
 2,
 5,
 4,
 2,
 1,
 4,
 4,
 5,
 3,
 2,
 5,
 5,
 4,
 5,
 5,
 4,
 4,
 5,
 5,
 2,
 2,
 5,
 4,
 2,
 1,
 4,
 4,
 5,
 3,
 2,
 5,
 5,
 4,
 5,
 5,
 4,
 4,
 5,
 5,
 2,
 2,
 5,
 4,
 2,
 1,
 4,
 4,
 5,
 3,
 2,
 5,
 5,
 4,
 5,
 5,
 4,
 4,
 5,
 5,
 2,
 2,
 5,
 4,
 2,
 1,
 4,
 4,
 5,
 3,
 2,
 5,
 5,
 4,
 5,
 5,
 4,
 4,
 5,
 5,
 2,
 2,
 5,
 4,
 2,
 1,
 4,
 4,
 5,
 3,
 2,
 5,
 5,
 4,
 5,
 5,
 4,
 4,
 5,
 5,
 2,
 2,
 5,
 4,
 2,
 1,
 4,
 4,
 5,
 3,
 2,
 5,
 5,
 4,
 5,
 5,
 4,
 4,
 5,
 5,
 2,
 2,
 5,
 4,
 2,
 1,
 4,
 4,
 5,
 3,
 2,
 5,
 5,
 4,
 5,
 5,
 4,
 4,
 5,
 5,
 2,
 2,
 5,
 4,
 2,
 1,
 4,
 4,
 5,
 3,
 2,
 5,
 5,
 4,
 5,
 5,
 4,
 4,
 5,
 5,
 2,
 2,
 5,
 4,
 2,
 1,
 4,
 4,
 5,
 3,
 2,
 5,
 5,
 4,
 5,
 5,
 4,
 4,
 5,
 5,
 2,
 2,
 5,
 4,
 2,
 1,
 4,
 4,
 5,
 3,
 2,
 5,
 5,
 4,
 5,
 5,
 4,
 4,
 5,
 5,
 2,


In [14]:
# vectorized 
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
ngram_vect = CountVectorizer(ngram_range=(1,1))
X_counts = ngram_vect.fit_transform(df['LemmText'])

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X_counts, y,test_size=0.3)
#0.3 mean the training set will be 70% and test set will be 30%

In [16]:
X_train

<3972x24260 sparse matrix of type '<class 'numpy.int64'>'
	with 228088 stored elements in Compressed Sparse Row format>

In [17]:
X_test

<1703x24260 sparse matrix of type '<class 'numpy.int64'>'
	with 100382 stored elements in Compressed Sparse Row format>

In [18]:
y_train

[4,
 5,
 4,
 4,
 5,
 5,
 4,
 3,
 5,
 4,
 4,
 4,
 2,
 4,
 2,
 5,
 5,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 3,
 5,
 2,
 3,
 5,
 4,
 5,
 5,
 4,
 2,
 5,
 2,
 4,
 4,
 5,
 4,
 2,
 2,
 4,
 2,
 3,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 4,
 5,
 5,
 4,
 1,
 2,
 4,
 2,
 4,
 4,
 2,
 4,
 1,
 5,
 5,
 2,
 4,
 2,
 4,
 5,
 4,
 2,
 2,
 5,
 5,
 4,
 4,
 4,
 5,
 4,
 3,
 5,
 5,
 5,
 5,
 4,
 5,
 5,
 5,
 2,
 4,
 5,
 4,
 2,
 3,
 4,
 4,
 5,
 4,
 5,
 5,
 3,
 1,
 2,
 5,
 3,
 5,
 5,
 3,
 5,
 4,
 5,
 5,
 4,
 4,
 4,
 2,
 5,
 2,
 2,
 5,
 2,
 4,
 5,
 4,
 5,
 5,
 4,
 2,
 4,
 5,
 2,
 5,
 5,
 2,
 2,
 4,
 4,
 5,
 2,
 2,
 4,
 5,
 4,
 5,
 5,
 5,
 4,
 5,
 4,
 5,
 5,
 5,
 5,
 2,
 5,
 2,
 4,
 5,
 2,
 5,
 4,
 4,
 5,
 5,
 5,
 4,
 5,
 5,
 4,
 4,
 5,
 2,
 4,
 1,
 4,
 5,
 4,
 3,
 5,
 3,
 4,
 4,
 4,
 5,
 5,
 4,
 3,
 5,
 2,
 5,
 5,
 5,
 5,
 1,
 4,
 5,
 4,
 3,
 1,
 4,
 4,
 5,
 5,
 5,
 2,
 5,
 1,
 2,
 5,
 5,
 3,
 5,
 3,
 5,
 2,
 1,
 5,
 5,
 5,
 3,
 4,
 1,
 4,
 2,
 3,
 4,
 4,
 4,
 4,
 2,
 4,
 5,
 5,
 5,
 5,
 3,
 4,
 2,
 4,
 4,
 2,


In [19]:
y_test 

[5,
 5,
 5,
 5,
 1,
 4,
 5,
 5,
 5,
 4,
 5,
 4,
 5,
 2,
 5,
 5,
 5,
 2,
 5,
 2,
 5,
 5,
 1,
 5,
 4,
 2,
 5,
 4,
 5,
 5,
 5,
 4,
 2,
 5,
 3,
 2,
 5,
 3,
 5,
 4,
 5,
 4,
 5,
 5,
 5,
 4,
 4,
 2,
 5,
 4,
 4,
 4,
 5,
 4,
 4,
 4,
 5,
 1,
 4,
 5,
 5,
 5,
 5,
 2,
 5,
 1,
 4,
 4,
 5,
 4,
 5,
 2,
 5,
 4,
 4,
 5,
 5,
 4,
 4,
 4,
 2,
 4,
 2,
 4,
 3,
 4,
 4,
 5,
 5,
 4,
 4,
 4,
 5,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 2,
 5,
 4,
 2,
 3,
 1,
 4,
 5,
 5,
 2,
 5,
 4,
 4,
 5,
 2,
 2,
 2,
 5,
 4,
 5,
 4,
 2,
 5,
 5,
 5,
 5,
 2,
 2,
 4,
 5,
 5,
 5,
 4,
 2,
 2,
 2,
 4,
 5,
 4,
 5,
 4,
 4,
 4,
 3,
 5,
 4,
 2,
 5,
 2,
 4,
 4,
 2,
 4,
 4,
 5,
 5,
 5,
 5,
 2,
 2,
 2,
 5,
 4,
 2,
 4,
 5,
 4,
 4,
 5,
 5,
 5,
 4,
 5,
 2,
 5,
 5,
 4,
 2,
 5,
 5,
 2,
 4,
 5,
 3,
 5,
 5,
 2,
 5,
 5,
 4,
 5,
 2,
 4,
 5,
 5,
 2,
 5,
 5,
 4,
 5,
 2,
 5,
 4,
 4,
 5,
 4,
 4,
 5,
 4,
 3,
 5,
 3,
 3,
 5,
 4,
 2,
 4,
 4,
 1,
 4,
 2,
 2,
 5,
 4,
 5,
 5,
 2,
 5,
 5,
 2,
 4,
 1,
 5,
 1,
 5,
 5,
 3,
 5,
 2,
 5,
 5,
 5,
 5,
 2,
 5,
 5,
 5,


In [20]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train,y_train)

NBpredictions = nb.predict(X_test)

In [21]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,NBpredictions))
print('\n')
print(classification_report(y_test,NBpredictions))

[[  0   1   0  24  54]
 [  0  41   0  74 215]
 [  0   1   0  24  55]
 [  0  13   0 182 324]
 [  0  11   0 144 540]]


              precision    recall  f1-score   support

           1       0.00      0.00      0.00        79
           2       0.61      0.12      0.21       330
           3       0.00      0.00      0.00        80
           4       0.41      0.35      0.38       519
           5       0.45      0.78      0.57       695

    accuracy                           0.45      1703
   macro avg       0.29      0.25      0.23      1703
weighted avg       0.43      0.45      0.39      1703



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [22]:
print("Confusion Matrix:\n", confusion_matrix(y_test, NBpredictions))
print("###################")
print("classification_report: ",'\n' ,classification_report(y_test, NBpredictions))


Confusion Matrix:
 [[  0   1   0  24  54]
 [  0  41   0  74 215]
 [  0   1   0  24  55]
 [  0  13   0 182 324]
 [  0  11   0 144 540]]
###################
classification_report:  
               precision    recall  f1-score   support

           1       0.00      0.00      0.00        79
           2       0.61      0.12      0.21       330
           3       0.00      0.00      0.00        80
           4       0.41      0.35      0.38       519
           5       0.45      0.78      0.57       695

    accuracy                           0.45      1703
   macro avg       0.29      0.25      0.23      1703
weighted avg       0.43      0.45      0.39      1703

